#!/usr/bin/env bash

session=$(find ~ ~/learning ~/projects -mindepth 1 -maxdepth 1 -type d | fzf)

if [[ -z "$session" ]]; then
    exit 1
fi

session_name=$(basename "$session" | tr . _)

if ! $(tmux has-session -t "$session_name" 2> /dev/null); then
    tmux new-session -s "$session_name" -c "$session" -d
fi

if [[ -z "$TMUX" ]]; then
    tmux attach -t "$session_name"
else
    tmux switch-client -t "$session_name"
fi

